# Generated by Django 2.2.4 on 2022-06-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
